geofencing-spec.html
Hopefully using ES6 doesn't break ReSpec's syntax highlighting.
=> Modernized the examples a bit..

README.md, index.html
=> Clarify Geolocation Sensor group ownership

index.html
=> Drop inline issues

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/33.html" title="Last updated on Aug 21, 2019, 2:43 PM UTC (e1e5792)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/33/69a8ee5...marcoscaceres:e1e5792.html" title="Last updated on Aug 21, 2019, 2:43 PM UTC (e1e5792)">Diff</a>
=> Editorial: fix xrefs

index.html, tidyconfig.txt
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/36.html" title="Last updated on Oct 2, 2019, 3:10 AM UTC (55a0f6d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/36/9a47a0e...marcoscaceres:55a0f6d.html" title="Last updated on Oct 2, 2019, 3:10 AM UTC (55a0f6d)">Diff</a>
=> Tidy up document

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/40.html" title="Last updated on May 22, 2020, 7:01 AM UTC (1ea25fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/40/33e5ae6...1ea25fd.html" title="Last updated on May 22, 2020, 7:01 AM UTC (1ea25fd)">Diff</a>
=> chore: update ReSpec usage

index.html
Closes #10
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/41.html" title="Last updated on May 21, 2020, 4:15 PM UTC (ddc63c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/41/3341e1e...ddc63c3.html" title="Last updated on May 21, 2020, 4:15 PM UTC (ddc63c3)">Diff</a>
=> Add feature policy support

index.html
=> Editorial: fix jump to undefined step

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/52.html" title="Last updated on Jul 24, 2020, 12:39 AM UTC (81659d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/52/617a8d4...81659d9.html" title="Last updated on Jul 24, 2020, 12:39 AM UTC (81659d9)">Diff</a>
=> Editorial: s/feature policy/permissions policy

index.html
Closes #61
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/62.html" title="Last updated on Mar 18, 2021, 9:38 PM UTC (4e91236)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/62/9f5d7e9...4e91236.html" title="Last updated on Mar 18, 2021, 9:38 PM UTC (4e91236)">Diff</a>
=> Default errorCallback to null

README.md, index.html
Closes #59
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/65.html" title="Last updated on Mar 23, 2021, 10:03 PM UTC (7575f84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/65/c0381e2...7575f84.html" title="Last updated on Mar 23, 2021, 10:03 PM UTC (7575f84)">Diff</a>
=> Editorial: call out examples more clearly + add explainer

index.html
Closes #50
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/72.html" title="Last updated on Apr 29, 2021, 4:30 AM UTC (4fe26ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/72/f888390...4fe26ed.html" title="Last updated on Apr 29, 2021, 4:30 AM UTC (4fe26ed)">Diff</a>
=> Editorial: reword .message i18n note

README.md
=> Typo Fix on Readme.md

index.html
Closes #82
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/86.html" title="Last updated on Jun 10, 2021, 4:54 AM UTC (6ca2be2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/86/f005a86...6ca2be2.html" title="Last updated on Jun 10, 2021, 4:54 AM UTC (6ca2be2)">Diff</a>
=> Editorial: link up implementation defined

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/89.html" title="Last updated on Jun 9, 2021, 6:27 AM UTC (eb87963)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/89/67cc9b6...eb87963.html" title="Last updated on Jun 9, 2021, 6:27 AM UTC (eb87963)">Diff</a>
=> Editorial: cleanup RS config

index.html, tidyconfig.txt
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/102.html" title="Last updated on Aug 12, 2021, 6:57 AM UTC (4f0fc91)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/102/2c0c516...4f0fc91.html" title="Last updated on Aug 12, 2021, 6:57 AM UTC (4f0fc91)">Diff</a>
=> chore: add change log since FPWD

index.html
Closes #114
Closes #113
Really sorry folks, this ended needing more changes than I had initially hoped (I found some additional bugs).  
@reillyeon, um, I don't expect you to review all this... I'm wonder if we should just take it, and then do a "full spec review"?
How should we proceed?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/118.html" title="Last updated on Jan 29, 2022, 12:46 AM UTC (e5481f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/118/87a31f6...e5481f8.html" title="Last updated on Jan 29, 2022, 12:46 AM UTC (e5481f8)">Diff</a>
=> fix "Queue a task" / "in parallel" usage

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/127.html" title="Last updated on Sep 21, 2022, 7:24 PM UTC (686d031)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/127/dfca449...marcoscaceres:686d031.html" title="Last updated on Sep 21, 2022, 7:24 PM UTC (686d031)">Diff</a>
=> Editorial: retire Marcos as Editor

index.html
Closes nothing
The following tasks have been completed: n/a
Implementation commitment: n/a
/cc @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/144.html" title="Last updated on Mar 17, 2024, 2:42 PM UTC (eb065dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/144/ef098b1...eb065dd.html" title="Last updated on Mar 17, 2024, 2:42 PM UTC (eb065dd)">Diff</a>
=> Added webapps as group

index.html
Would like to resume editorial duties on this spec, now that it's a joint deliverable.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/143.html" title="Last updated on Mar 12, 2024, 3:02 AM UTC (f9e99d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/143/ef098b1...marcoscaceres:f9e99d1.html" title="Last updated on Mar 12, 2024, 3:02 AM UTC (f9e99d1)">Diff</a>
=> chore: bring Marcos out of retirement

index.html
as title. proceed once https://github.com/speced/respec/pull/4737 has settled.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/168.html" title="Last updated on Jun 17, 2024, 5:43 PM UTC (b5704c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/168/0fb6edc...b5704c6.html" title="Last updated on Jun 17, 2024, 5:43 PM UTC (b5704c6)">Diff</a>
=> removed revisionTypes

.github/workflows/auto-publish-errata.yml
Closes none
see #166 for relationate
open Qs
- be better to change action name??
- any other files required to be processed using respec?
=> Added ipr to gh-action

index.html
"Candidate Correction" -> "Candidate Addition"
Related PR #162
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/175.html" title="Last updated on Sep 12, 2024, 9:39 AM UTC (a349393)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/175/9d5829e...a349393.html" title="Last updated on Sep 12, 2024, 9:39 AM UTC (a349393)">Diff</a>
=> chore: fix purple box marker
