w3c/geolocation

index.html

Rename exposed interfaces
Fix #19

Remove [NoInterfaceObject]

---

index.html

They were prefixed in https://github.com/w3c/geolocation-api/pull/20
when removing [NoInterfaceObject], to avoid polluting the global
namespace with generic interface names.
However, no other specs that add an object to navigator prefix the
interface name with Navigator. Examples:
https://storage.spec.whatwg.org/#api
https://w3c.github.io/clipboard-apis/#navigator-interface
https://w3c.github.io/keyboard-lock/#navigator-interface
https://w3c.github.io/permissions/#navigator-and-workernavigator-extension
https://w3c.github.io/presentation-api/#interface-presentation
https://w3c.github.io/webappsec-credential-management/#framework-credential-management
https://wicg.github.io/media-capabilities/#navigators-extensions
https://wicg.github.io/mediasession/#the-mediasession-interface …

Rename NavigatorGeolocation* interfaces to Geolocation*

---

index.html

https://github.com/heycam/webidl/issues/758
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/27.html" title="Last updated on Aug 9, 2019, 11:33 AM UTC (2e29610)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/27/66cd99c...2e29610.html" title="Last updated on Aug 9, 2019, 11:33 AM UTC (2e29610)">Diff</a>

Align with IDL dictionary changes

---

index.html

These are required, as per ReSpec complaining about them being missing :)
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/32.html" title="Last updated on Aug 20, 2019, 5:46 AM UTC (021c64d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/32/69a8ee5...marcoscaceres:021c64d.html" title="Last updated on Aug 20, 2019, 5:46 AM UTC (021c64d)">Diff</a>

Editorial: Add Exposed extended attribute

---

index.html

Closes #25
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/34.html" title="Last updated on Aug 28, 2019, 11:58 PM UTC (78a4fff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/34/eea2561...marcoscaceres:78a4fff.html" title="Last updated on Aug 28, 2019, 11:58 PM UTC (78a4fff)">Diff</a>

Add SecureContext and API behavior of browsers

---

index.html

Minor fix: the PositionOptions dictionary definition was labelled as an interface.
I left the ID as `position_options_interface` deliberately. There seem to be a lot of scattered links around pointing to it and I figured it was better to err on the side of leaving those links working.
***
<a href="https://pr-preview.s3.amazonaws.com/bathos/geolocation-api/pull/38.html" title="Last updated on Nov 24, 2019, 5:39 AM UTC (89d4ce0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/38/a11d0d0...bathos:89d4ce0.html" title="Last updated on Nov 24, 2019, 5:39 AM UTC (89d4ce0)">Diff</a>

Typo: PositionOptions is a dictionary rather than an interface

---

index.html

Closes #24
Checked all three browsers, no one supports what was in the spec.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 21, 2020, 6:32 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fgeolocation-api%2Fpull%2F39%2F3341e1e.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fgeolocatio …

fix: callbacks are not EventHandlers

---

index.html

Depends on #46 
Closes #50
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/51.html" title="Last updated on Jul 28, 2020, 10:29 PM UTC (ea68651)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/51/61929d3...ea68651.html" title="Last updated on Jul 28, 2020, 10:29 PM UTC (ea68651)">Diff</a>

Editorial: fix up .message text

---

index.html

Closes #56
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/63.html" title="Last updated on Mar 22, 2021, 1:33 AM UTC (3518ac5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/63/c0381e2...3518ac5.html" title="Last updated on Mar 22, 2021, 1:33 AM UTC (3518ac5)">Diff</a>

Editorial: remove RFC2119 words from Requirements

---

index.html

Addresses https://github.com/w3ctag/design-reviews/issues/529
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/66.html" title="Last updated on Mar 23, 2021, 6:58 AM UTC (9e8c701)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/66/6256b91...9e8c701.html" title="Last updated on Mar 23, 2021, 6:58 AM UTC (9e8c701)">Diff</a>

Editorial: recipients are not a conformance class

---

index.html

Closes #54
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/68.html" title="Last updated on Mar 25, 2021, 2:56 AM UTC (0763502)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/68/fd2cfbc...0763502.html" title="Last updated on Mar 25, 2021, 2:56 AM UTC (0763502)">Diff</a>

Hook into Permissions API to get permission

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/76.html" title="Last updated on May 7, 2021, 6:04 AM UTC (61c36b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/76/2815d2c...61c36b4.html" title="Last updated on May 7, 2021, 6:04 AM UTC (61c36b4)">Diff</a>

Editorial: update test suite link

---

index.html

per https://github.com/w3c/transitions/issues/331#issuecomment-845099747
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/77.html" title="Last updated on May 22, 2021, 7:25 AM UTC (3c7a788)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/77/14f1469...3c7a788.html" title="Last updated on May 22, 2021, 7:25 AM UTC (3c7a788)">Diff</a>

Update the shortname

---

.github/workflows/pr-push.yml

For when the document is up on TR, we can start auto-publishing.

chore(github/workflows/pr-push): autopub

---

index.html

Typo fixes and number separators.
CC: @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/tomayac/geolocation-api/pull/83.html" title="Last updated on May 31, 2021, 7:15 AM UTC (dc74144)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/83/ff9de8d...tomayac:dc74144.html" title="Last updated on May 31, 2021, 7:15 AM UTC (dc74144)">Diff</a>

Some suggestions and fixes

---

index.html

Closes #81
PLEASE DON'T COPY THIS - Follow https://github.com/w3c/respec/issues/3571
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/88.html" title="Last updated on Jun 9, 2021, 6:20 AM UTC (acb906d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/88/67cc9b6...acb906d.html" title="Last updated on Jun 9, 2021, 6:20 AM UTC (acb906d)">Diff</a>

Editorial: use WebIDL style prose for method calls

---

index.html

Closes #80
@annevk, I did as you suggested:
1. Collapsed the "Acquire a watch id" labelled steps. 
1. "Run these steps [=in parallel=]:". 
1. Tied all callback invocations to a microtask.
1. And now I return |watchId| as the final step. 
As I had to re-indent the algorithm, probably best viewed in PR-Preview.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/87.html" title="Last updated on Jul 8, 2021, 4:18 AM UTC (c65844e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/87/2ae2301...c65844e.html" title="Last updated on Jul 8, 2021, 4:18 AM UTC (c65844e)">Diff</a>

Add "geolocation task queue"

---

index.html

Closes #78 
cc @rakina
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/90.html" title="Last updated on Jul 13, 2021, 10:11 PM UTC (e07e3bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/90/e3f4d84...e07e3bf.html" title="Last updated on Jul 13, 2021, 10:11 PM UTC (e07e3bf)">Diff</a>

Gracefully handle documents that are not fully active

---

index.html

Closes #96 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/97.html" title="Last updated on Jul 27, 2021, 8:29 AM UTC (b92947d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/97/f4605e5...b92947d.html" title="Last updated on Jul 27, 2021, 8:29 AM UTC (b92947d)">Diff</a>

Callback with error if doc is not fully active

---

index.html

Closes #95 - @reillyeon, please see https://github.com/w3c/geolocation-api/issues/95#issuecomment-888988557 for rationale for change.  
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/100.html" title="Last updated on Jul 30, 2021, 1:26 AM UTC (e19aa52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/100/3d8edf8...e19aa52.html" title="Last updated on Jul 30, 2021, 1:26 AM UTC (e19aa52)">Diff</a>

Return 0 when watchPosition() errors

---

index.html

Also integrates a little bit better with Permission API, but defining itself as a "powerful feature".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/105.html" title="Last updated on Sep 30, 2021, 3:31 AM UTC (70c4611)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/105/2b82e7d...70c4611.html" title="Last updated on Sep 30, 2021, 3:31 AM UTC (70c4611)">Diff</a>

Editorial: update permission policy usage

---

index.html

Closes #103
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/104.html" title="Last updated on Oct 11, 2021, 4:47 AM UTC (85f8eda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/104/2b82e7d...85f8eda.html" title="Last updated on Oct 11, 2021, 4:47 AM UTC (85f8eda)">Diff</a>

Switch DOMTimeStamp to EpochTimeStamp

---

index.html

Closes #107 
* <del>Modified Web platform tests</del> - can't be tested directly. 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/109.html" title="Last updated on Nov 23, 2021, 11:51 PM UTC (ed4372e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/109/9098051...ed4372e.html" title="Last updated on Nov 23, 2021, 11:51 PM UTC (ed4372e)">Diff</a>

Handle OS permission

---

index.html

Closes #69 
Closes #54
Depends on https://github.com/w3c/permissions/pull/287 and https://github.com/whatwg/html/pull/7337
Try to be broadly accommodating to what browses do with respect to Geolocation permission lifetimes. I prioritized "single session" permissions, while accommodating what Chrome does (you can navigate around... only when you close the browser window/tab does it reset). I also allowed for what Brave does (time based).   
* <del>Modified Web platform tests</del> (not testable)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/108.html" title="Last updated on Nov 23, 2021, 11:29 PM UTC (d86891b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/108/9098 …

Suggest permission lifetimes

---

index.html

@noamr, r? 
Noam, can you sanity check something for me... in the HTML spec, it's not really clear why the [=page visibility change steps=] take the first argument ("visible", for instance)... at least, they don't seem to be used in the steps themselves or am I missing something?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/110.html" title="Last updated on Nov 24, 2021, 1:14 AM UTC (bf06492)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/110/a1531cb...bf06492.html" title="Last updated on Nov 24, 2021, 1:14 AM UTC (bf06492)">Diff</a>

Editorial: make use of HTML's page visibility change steps

---

index.html

The W3C now prefers we split these into separate sections.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 24, 2022, 7:44 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fgeolocation-api%2Fc943f124298c293d1fadaf42ef25882509ad71b1%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 29716 ms exceeded
```
_If you don't have enough information above to solve the error by yourself (or …

Editorial: split Privacy and Security considerations

---

index.html

I'd like to formally acknowledge Reilly as co-editor of the Geolocation spec. 
Reilly has provided extensive feedback and spotted many bugs since we started the rewrite, while also diligently enduring my many overly large pull requests. This is a small way to say thanks and to acknowledge how much better the spec is thanks to Reilly's contributions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/119.html" title="Last updated on Jan 31, 2022, 12:22 AM UTC (e9a0cd1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/119/c18cd45...e9a0cd1.html" title="Last updated on Jan 31, 2022, 12:22 AM UTC (e9a0cd1)">Diff</a>

Editorial: acknowledge Reilly Grant as co-editor

---

index.html

Closes #125
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/128.html" title="Last updated on Sep 21, 2022, 7:42 PM UTC (983993c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/128/dfca449...marcoscaceres:983993c.html" title="Last updated on Sep 21, 2022, 7:42 PM UTC (983993c)">Diff</a>

Editorial: use [=this=] to get global

---

index.html

Closes #126
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/geolocation-api/pull/129.html" title="Last updated on Sep 22, 2022, 1:32 AM UTC (134c8c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/129/eaa69f3...marcoscaceres:134c8c5.html" title="Last updated on Sep 22, 2022, 1:32 AM UTC (134c8c5)">Diff</a>

Editorial: fix 'in parallel' usage

---

index.html

[=default allowlist=] -> [=policy-controlled feature/default allowlist=]
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/133.html" title="Last updated on Mar 1, 2023, 10:21 PM UTC (c45df09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/133/a95f47a...c45df09.html" title="Last updated on Mar 1, 2023, 10:21 PM UTC (c45df09)">Diff</a>

Editorial: Fix references to "default allowlist"

---

index.html

Replace "decimal degrees" with "a real number of degrees" for greater clarity and specifically refer to the WGS84 coordinate system for latitude and longitude the way it is for altitude.
Closes #135 and #136.
CC @mgiuca and @jyasskin.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/138.html" title="Last updated on Apr 10, 2024, 2:44 AM UTC (dc2b830)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/138/7082b4e...dc2b830.html" title="Last updated on Apr 10, 2024, 2:44 AM UTC (dc2b830)">Diff</a>

Correction: Clarify units and reference geodetic system for latitude and longitude

---

index.html

Closes #145 
* https://github.com/WebKit/WebKit/pull/27063
*  https://github.com/WebKit/WebKit/pull/27127 
* https://chromium-review.googlesource.com/c/chromium/src/+/5446324
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/147.html" title="Last updated on Apr 15, 2024, 9:00 PM UTC (c9c9574)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/147/10b168f...c9c9574.html" title="Last updated on Apr 15, 2024, 9:00 PM UTC (c9c9574)">Diff</a>

Addition: expose .toJSON() on GeolocationCoordinates + GeolocationPosition

---

index.html

Closes #148
Ok, so we are going to show Corrections and Additions like this: 
All we need to do is make sure we label the each new commit correctly.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/149.html" title="Last updated on Apr 11, 2024, 7:44 AM UTC (ff9728a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/149/5391d57...ff9728a.html" title="Last updated on Apr 11, 2024, 7:44 AM UTC (ff9728a)">Diff</a>

chore: put in updatable rec infra

---

index.html

Allows spec to be viewed in dark mode, if user wants...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/152.html" title="Last updated on Apr 30, 2024, 4:17 AM UTC (91f337e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/152/5f9a675...91f337e.html" title="Last updated on Apr 30, 2024, 4:17 AM UTC (91f337e)">Diff</a>

chore: enable dark mode

---

README.md

Related to #145 
Documentation (new feature):

docs: show new .toJSON() capability

---

index.html

Closes #156 
Implementation commitment (and no objections):
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/157.html" title="Last updated on Jun 4, 2024, 2:25 AM UTC (e3048dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/157/664f556...e3048dd.html" title="Last updated on Jun 4, 2024, 2:25 AM UTC (e3048dd)">Diff</a>

Correction: check for non-secure contexts

---

.github/workflows/auto-publish-errata.yml
errata.html

This will solve recent PR merge check issues, with removing W3C_ lines.
Also fixed errata.html on wrong repository name, etc.
Background:
- built spec page (Overview.html) points to errata.html at github.io but not in the same directory in /TR/
- there seems no available specStatus configuration of respec, which could be published to /TR/, like base nor LD
- even if we want to publish errata.html into /TR/ we shall run echidna publication at once contains both Overview.html and errata.html (but not running spec-prod twice)

Disable /TR/ publication for errata.html

---

index.html

required text change per publication rules. (see details/backgrounds as email)
since not all of error is fixed with this, marking as draft.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/159.html" title="Last updated on Jun 9, 2024, 3:44 PM UTC (8742d86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/159/b358dad...8742d86.html" title="Last updated on Jun 9, 2024, 3:44 PM UTC (8742d86)">Diff</a>

minor text fix, for pubrules

---

index.html

This PR contains a set of minor editorial corrections which should be applied prior to republication:
* Adds a missing semicolon to the `clearWatch()` example.
* Adds a missing "informative" class to the `timeout` example.
* Removes two unnecessary instances of the word "the" from the proposed changes to the fully active checks.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/161.html" title="Last updated on Jun 11, 2024, 7:57 PM UTC (32f2ab8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/161/12327c4...32f2ab8.html" title="Last updated on Jun 11, 2024, 7:57 PM UTC (32f2ab8)">Diff</a>

Editorial: Minor corrections prior to republication

---

index.html

As with altitudeAccuracy, implementations provide this value in meters and that is what MDN documents but this was not specified.
Fixed #160.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/162.html" title="Last updated on Jun 11, 2024, 8:15 PM UTC (bded772)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/162/12327c4...bded772.html" title="Last updated on Jun 11, 2024, 8:15 PM UTC (bded772)">Diff</a>

Addition: Define units for accuracy

---

index.html

Enhance the "Acquire a Position" algorithm to include explicit data type definitions and unit specifications for each piece of acquired position data, aligning with the [[WGS84]] coordinate system standards. This update ensures each parameter (latitude, longitude, altitude, etc.) is clearly defined at the point of data acquisition.
Additionally, refine the handling of cached position data within the algorithm. Introduce conditional logic to terminate the algorithm early if a valid cached position is used, preventing unnecessary data acquisition steps. This change improves efficiency and clarity in the geolocation process, ensuring that position data is handled correctly based on its freshness and accuracy requirements.
Key Changes:
- Define explicit data types and units for latitude, …

Correction: Update acquisition algorithm to define data types and handle cached positions

---

CONTRIBUTING.md
README.md
errata.html
index.html
reports/PR_imp_report.html

Closes #154
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/164.html" title="Last updated on Jun 14, 2024, 7:50 AM UTC (205edbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/164/1360745...205edbd.html" title="Last updated on Jun 14, 2024, 7:50 AM UTC (205edbd)">Diff</a>

Editorial: rename spec to Geolocation

---

index.html

fix regression by 2d0383a
Closes nothing.
also need to sync gh-pages branch to main, for /reports/ directory.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/166.html" title="Last updated on Jun 17, 2024, 4:34 PM UTC (cfdd805)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/166/0fb6edc...cfdd805.html" title="Last updated on Jun 17, 2024, 4:34 PM UTC (cfdd805)">Diff</a>

link fix for ipr

---

index.html

This algorithm can now handle the need to report an exception thrown by the callback. Some small tweaks are made for consistency with other specifications.
Part of whatwg/webidl#1425.
Implementation commitment (and no objections): n/a (non-normative change)
Documentation (new feature): n/a (non-normative change)
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/w3c-geolocation/pull/172.html" title="Last updated on Aug 8, 2024, 9:19 PM UTC (2a69705)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/172/b0ca499...jeremyroman:2a69705.html" title="Last updated on Aug 8, 2024, 9:19 PM UTC (2a69705)">Diff</a>

Editorial: Update use of WebIDL "invoke a callback function"

---

index.html

This ammends the existing correction clarifying the units and conditions for the heading property. This matches existing implementations which return null in this scenario.
Closes #171.
Implementation commitment (and no objections):
Documentation (new feature):
For documentation, either create an [issue](https://github.com/mdn/content/issues) or pull request in [MDN's Content](https://github.com/mdn/content) repo  - providing as much information as you can. PR is prefered.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/173.html" title="Last updated on Aug 14, 2024, 7:46 PM UTC (551519b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/173/9ae72d3...551519b.html" title="Last updated on Aug 14, 2024, …

Correction: Use null instead of NaN when stationary

---

CONTRIBUTING.md
index.html

Closes #146 
Implementation commitment (and no objections):
Documentation (new feature):
* ~[ ] Updated implementation report~ N/A
* ~[ ] Pinged MDN~ N/A. will be exposed via WebDriver BiDi
* ~[ ] Added example to README or spec~ N/A. will be exposed via WebDriver BiDi
For documentation, either create an [issue](https://github.com/mdn/content/issues) or pull request in [MDN's Content](https://github.com/mdn/content) repo  - providing as much information as you can. PR is prefered.
***
<a href="https://pr-preview.s3.amazonaws.com/sadym-chromium/geolocation/pull/183.html" title="Last updated on Apr 11, 2025, 3:00 PM UTC (19546d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/183/841f1c6...sadym-chromium:19546d5.html" …

Addition: support geolocation emulation

---

index.html

Closes #199
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/201.html" title="Last updated on Sep 23, 2025, 3:57 AM UTC (680d722)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/201/a4f1002...680d722.html" title="Last updated on Sep 23, 2025, 3:57 AM UTC (680d722)">Diff</a>

chore: fixup commit history

---

index.html

Closes #194
This pull request adds documentation to clarify how the Geolocation API is accessed via the `navigator` attribute. The most important change is an explanatory section in the HTML documentation.
Documentation improvement:
* Added a new `<h3>` section titled "`navigator` attribute" to `index.html`, describing that the `geolocation` attribute on `navigator` is the entry point for accessing the Geolocation API.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/pull/202.html" title="Last updated on Oct 3, 2025, 8:22 AM UTC (02364fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation/202/30713be...02364fe.html" title="Last updated on Oct 3, 2025, 8:22 AM UTC (02364fe)">Diff</a>

Editorial: define geolocation attribute
